version: '3'

services:
  
  nodejs-gympoint:
    container_name: nodejs-gympoint
    build: '.'
    entrypoint: ["./init.sh"]
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-gympoint
      - jobs-gympoint
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres-gympoint:
    container_name: postgres-gympoint
    image: postgres:11
    volumes:
      - postgres-gympoint-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect
    ports:
      - '5432:5432'      


  jobs-gympoint:
    container_name: jobs-gympoint
    build: .
    command: yarn queue
    depends_on: 
      - redis-gympoint
    networks:
      - app-connect

  redis-gympoint:
    container_name: redis-gympoint
    image: bitnami/redis:latest
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-gympoint-data:/data
    networks:
      - app-connect
    
volumes:
  postgres-gympoint-data:
  redis-gympoint-data:

networks:
  app-connect:
      driver: bridge